export const agentTools = [
  {
    id: 'codex',
    name: 'Codex',
    team: 'OpenAI',
    category: '美国工具',
    mark: '◎',
    description: '在终端、编辑器与应用中推进编程任务。',
    url: 'https://openai.com/codex/',
    ready: true,
  },
  {
    id: 'claude-code',
    name: 'Claude Code',
    team: 'Anthropic',
    category: '美国工具',
    mark: '✳',
    description: '在代码库中完成开发、调试与重构。',
    url: 'https://claude.com/product/claude-code',
    ready: false,
  },
  {
    id: 'gemini-cli',
    name: 'Gemini CLI',
    team: 'Google',
    category: '美国工具',
    mark: '✦',
    description: '将 Gemini 接入终端中的开发工作流。',
    url: 'https://geminicli.com/',
    ready: false,
  },
  {
    id: 'cursor',
    name: 'Cursor',
    team: 'Anysphere',
    category: '美国工具',
    mark: '↗',
    description: '围绕 AI Agent 构建的代码编辑器。',
    url: 'https://cursor.com/',
    ready: false,
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    team: 'GitHub',
    category: '美国工具',
    mark: 'GH',
    description: '连接编辑器与 GitHub 开发流程的编程工具。',
    url: 'https://github.com/features/copilot',
    ready: false,
  },
  {
    id: 'qwen-code',
    name: 'Qwen Code',
    team: '通义千问',
    category: '国产工具',
    mark: 'Q',
    description: '支持终端与编辑器工作流的开源编程 Agent。',
    url: 'https://github.com/QwenLM/qwen-code',
    ready: false,
  },
  {
    id: 'kimi-code',
    name: 'Kimi Code',
    team: '月之暗面',
    category: '国产工具',
    mark: 'K',
    description: '面向 CLI 与 IDE 开发场景的编程 Agent。',
    url: 'https://www.kimi.com/code',
    ready: false,
  },
  {
    id: 'trae',
    name: 'TRAE / TraeCode',
    team: 'TRAE',
    category: '国产工具',
    mark: 'T',
    description: 'TRAE 旗下的 AI 编程工具。',
    url: 'https://www.trae.cn/',
    ready: false,
  },
  {
    id: 'codebuddy',
    name: 'CodeBuddy',
    team: '腾讯云',
    category: '国产工具',
    mark: 'CB',
    description: '腾讯云的 AI 编程助手。',
    url: 'https://copilot.tencent.com/',
    ready: false,
  },
  {
    id: 'opencode',
    name: 'OpenCode',
    team: 'Anomaly / 开源社区',
    category: '开放生态',
    mark: 'OC',
    description: '连接多家模型服务的开源编程 Agent。',
    url: 'https://opencode.ai/',
    ready: false,
  },
];
export const agentCategories = ['美国工具', '国产工具', '开放生态'];
